export const ADD_REQUEST = 'ADD_REQUEST';
export const ADD_REQUEST_START = 'ADD_REQUEST_START';
export const ADD_REQUEST_FAIL = 'ADD_REQUEST_FAIL';
export const ADD_REQUEST_SUCCESS = 'ADD_REQUEST_SUCCESS';

export const FETCH_REQUESTS_START = 'FETCH_REQUESTS_START';
export const FETCH_REQUESTS_SUCCESS = 'FETCH_REQUESTS_SUCCESS';
export const FETCH_REQUESTS_FAIL = 'FETCH_REQUESTS_FAIL';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCSESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_LOGOUT = 'LOGIN_LOGOUT';