export const ADD_REQUESTS = 'ADD_REQUESTS';
export const ADD_REQUESTS_START = 'ADD_REQUESTS_START';
export const ADD_REQUESTS_FAIL = 'ADD_REQUESTS_FAIL';
export const ADD_REQUESTS_SUCCESS = 'ADD_REQUESTS_SUCCESS';
export const REMOVED_TO_FALSE_REQUEST = 'REMOVED_TO_FALSE_REQUEST';

export const REMOVE_REQUESTS = 'REMOVE_REQUESTS';
export const REMOVE_REQUESTS_START = 'REMOVE_REQUESTS_START';
export const REMOVE_REQUESTS_FAIL = 'REMOVE_REQUESTS_FAIL';
export const REMOVE_REQUESTS_SUCCESS = 'REMOVE_REQUESTS_SUCCESS';
export const REMOVED_TO_FALSE = 'REMOVED_TO_FALSE';

export const FETCH_REQUESTS_START = 'FETCH_REQUESTS_START';
export const FETCH_REQUESTS_SUCCESS = 'FETCH_REQUESTS_SUCCESS';
export const FETCH_REQUESTS_FAIL = 'FETCH_REQUESTS_FAIL';
export const FECTH_APPROVE_SUCCESS='FECTH_APPROVE_SUCCESS';
export const FECTH_REJECT_SUCCESS='FECTH_REJECT_SUCCESS'

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCSESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_LOGOUT = 'LOGIN_LOGOUT';